name: Keep Render API Alive

on:
  schedule:
    - cron: '*/10 * * * *'  # Runs every 10 minutes

jobs:
  keep_alive:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render API
        run: curl -s https://financial-terminal.onrender.com/calculate_var
